
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 38;
  public static final int READINT = 32;
  public static final int CASE = 7;
  public static final int CAR = 13;
  public static final int DOUBLE = 53;
  public static final int INLCOM = 49;
  public static final int CDR = 14;
  public static final int LPAREN = 19;
  public static final int SEMI = 21;
  public static final int INT = 50;
  public static final int PRINTLN = 30;
  public static final int MINUS = 34;
  public static final int LSCONCAT = 47;
  public static final int CMP = 52;
  public static final int RPAREN = 20;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int FUN = 2;
  public static final int OR = 41;
  public static final int COMMA = 24;
  public static final int BWOR = 44;
  public static final int CALL = 5;
  public static final int DIV = 36;
  public static final int PLUS = 33;
  public static final int ASSIGN = 39;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int TRUE = 55;
  public static final int error = 1;
  public static final int LSQBRAC = 27;
  public static final int ISEQUAL = 17;
  public static final int MUL = 35;
  public static final int RSQBRAC = 26;
  public static final int MOD = 37;
  public static final int ISPAIR = 15;
  public static final int PAIR = 12;
  public static final int EQU = 25;
  public static final int COLON = 28;
  public static final int LBRACE = 22;
  public static final int ELSE = 9;
  public static final int READ = 31;
  public static final int ISEQV = 16;
  public static final int LIST = 46;
  public static final int EMPLS = 48;
  public static final int SUBSTR = 18;
  public static final int LET = 6;
  public static final int THEN = 11;
  public static final int RBRACE = 23;
  public static final int END = 10;
  public static final int STRING = 54;
  public static final int PROC = 3;
  public static final int DEF = 4;
  public static final int FALSE = 56;
  public static final int BWNOT = 45;
  public static final int BWAND = 43;
  public static final int VAR = 51;
  public static final int PRINT = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUN",
  "PROC",
  "DEF",
  "CALL",
  "LET",
  "CASE",
  "IF",
  "ELSE",
  "END",
  "THEN",
  "PAIR",
  "CAR",
  "CDR",
  "ISPAIR",
  "ISEQV",
  "ISEQUAL",
  "SUBSTR",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "EQU",
  "RSQBRAC",
  "LSQBRAC",
  "COLON",
  "PRINT",
  "PRINTLN",
  "READ",
  "READINT",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "POW",
  "ASSIGN",
  "AND",
  "OR",
  "NOT",
  "BWAND",
  "BWOR",
  "BWNOT",
  "LIST",
  "LSCONCAT",
  "EMPLS",
  "INLCOM",
  "INT",
  "VAR",
  "CMP",
  "DOUBLE",
  "STRING",
  "TRUE",
  "FALSE"
  };
}

