
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 20;
  public static final int AND = 23;
  public static final int BWOR = 27;
  public static final int ELSE = 12;
  public static final int PLUS = 16;
  public static final int INT = 30;
  public static final int OR = 24;
  public static final int RBRACE = 7;
  public static final int RPAREN = 4;
  public static final int SEMI = 5;
  public static final int NOT = 25;
  public static final int END = 13;
  public static final int POW = 21;
  public static final int TRUE = 14;
  public static final int IF = 11;
  public static final int LPAREN = 3;
  public static final int COLON = 10;
  public static final int LBRACE = 6;
  public static final int COMMA = 8;
  public static final int CMP = 32;
  public static final int EOF = 0;
  public static final int DIV = 19;
  public static final int MINUS = 17;
  public static final int FALSE = 15;
  public static final int error = 1;
  public static final int BWAND = 26;
  public static final int ASSIGN = 22;
  public static final int LSCONCAT = 29;
  public static final int MUL = 18;
  public static final int BWNOT = 28;
  public static final int EQU = 9;
  public static final int VAR = 31;
  public static final int FUN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUN",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "EQU",
  "COLON",
  "IF",
  "ELSE",
  "END",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "POW",
  "ASSIGN",
  "AND",
  "OR",
  "NOT",
  "BWAND",
  "BWOR",
  "BWNOT",
  "LSCONCAT",
  "INT",
  "VAR",
  "CMP"
  };
}

